### ISSUE TITLE
Examples are not generating

### ISSUE THREAD

**Issue by Patrick-Ullrich** [smart-on-fhir/health-cards#190]
I pulled the repo yesterday and was unable to generate examples locally - hours later I noticed that https://spec.smarthealth.cards/examples/index.md shows a 404 now as well. 

Reproduce:
1. cd generate-examples
2. npm run generate-keys
3. npm run generate-examples

`/node_modules/got/dist/source/core/index.js:953
            error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                              ^
RequestError: certificate has expired
    at ClientRequest.<anonymous> (/Users/patrickullrich/src/health-cards/generate-examples/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (/Users/patrickullrich/src/health-cards/generate-examples/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)`

**Comment by jmandel** [comment]
Thanks for the report! Will evaluate ASAP.

**Comment by jmandel** [comment]
Should be fixed by https://github.com/smart-on-fhir/health-cards/commit/f3336d65201dbd384d06bf937438cab5239fedf5 (HL7.org cert issues; I'm just going to include the example bundle in this repo so we don't hit this again.)

**Comment by jmandel** [comment]
Also, really sorry for the frustrating experience here @Patrick-Ullrich. I know what debugging this kind of thing can feel like.
